### ISSUE TITLE
Error 37 (Item.SellerProfiles.SellerShippingProfile.ShippingProfileID)

### ISSUE THREAD

**Issue by vinvin27** [202ecommerce/ebay2#13]
Hello, j'ai cette erreur dans mes annonces, elles sont toutes rejetées :

"37 : Les données saisies pour la balise sont manquantes ou ne sont pas valides. Veuillez consulter votre documentation de l'API.(Item.SellerProfiles.SellerShippingProfile.ShippingProfileID)"

Une idée ?

j'ai la derniere version du plugin et j'utilise PS 1.6.1.24

**Comment by Diagavignon** [comment]
Bonjour 

Pareil pour moi 

j'ai mis la derniere version essaye de mettre un nouveau token sur ebay developper rien a faire 

prestashop 1.6.1.23

**Comment by bogdan202** [comment]
Hello, 
According to the error message, the most likely cause is the module cannot create a shipping rule on eBay. Please, check if both tokens are configured and valid. See more details in this article https://desk.202-ecommerce.com/portal/fr/kb/articles/erreur-37-synchronisation-produits

**Comment by vinvin27** [comment]
Hello @bogdan202 

Thanks you for your help, I found this link yesterday but unable to fix it. When I filled API credentials, and click on "cree le token OAUTH" button, its going back to extensions list....

So not able to get oauth token and fix catalog :(

**Comment by bogdan202** [comment]
@vinvin27 
I didn't understand what exactly happens when you click the button 'Cree le token'.
If the popup with configurations appears, it looks like some configuration isn't correct.
If the page is refreshed and nothing happens, then it looks like you set the URL of your shop in the field 'Your branded eBay Production Sign In (OAuth)'
![Selection_018](https://user-images.githubusercontent.com/44570209/203373016-d78eb102-9597-4a8f-9824-47dfab8c241b.png)

You'll find the correct value for this configuration in your eBay developer account

![Selection_017](https://user-images.githubusercontent.com/44570209/203373135-580f7850-84c6-484d-9d10-9d8b74f1c83b.png)

**Comment by vinvin27** [comment]
I understand something, when debugging : 

I can see, I'm going to scope URLs then : [/figadmin/index.php?controller=AdminTokenListener&token=ffa868dcf24f65b3d4b5e8f2cf4b5eed&error=invalid_scope]
and then the extension list

**Comment by vinvin27** [comment]
Ok fix it. I take the scope URL from ebay developper instead of takes them from my profil. In ebay developper scope URL are not encoded, it mean the are space between url. If you save on boarding popup, extension encode URL and transform space into %2F so I guess this is something wrong on my copy/past.

Oh btw, we are getting encoding issue (with accent or UTF8?) :  
"21919303 : The item specific TypeÂ is missing.Â Add Type to this listing, enter a valid value, and then try again.(The item specific TypeÂ is missing.)"

**Comment by vinvin27** [comment]
Ok so all is good on my site except the encoding issue :)

**Comment by fpanico82** [comment]
Hi,
The encoding problem has been fixed in version 2.2.6. Have you updated the module?

Francesco
202 ecommerce
