### ISSUE TITLE
Ebay Order sync error in prestashop for the price.

### ISSUE THREAD

**Issue by sireris** [202ecommerce/ebay2#17]
i noted that some order arent synced and give the error "Product price less than 0.1 or product not found"
![Screenshot 2022-12-24 at 17-05-42 Gestione Moduli •](https://user-images.githubusercontent.com/41742637/209443539-2b9041bb-3c40-46d8-8679-482f7986e302.png)

**Comment by fpanico82** [comment]
Hi,
I guess the error "Product price less than 0.1 or product not found" happens because the module cannot define the product to add to the order. For example, if a product was not created by the eBay module (the product was created manually or by another application). This sometimes happens when the customer manually changes the SKU of the product.

Francesco
202 ecommerce
