### ISSUE TITLE
Multiple sign-in URL per keyset with OAuth

### ISSUE THREAD

**Issue by tom-combet** [202ecommerce/ebay2#6]
![image](https://user-images.githubusercontent.com/48719560/189366510-e0bcbd0f-0577-433a-a70f-21d61dcb1568.png)

I get this alert when I try to enable OAuth for a second RuName in the same keyset. I'm indeed trying to connect a second PrestaShop website to the same eBay shop.
Can you confirm that I need to create one keyset per PrestaShop application? Just wanted to be sure because the process is quite fastidious, and I have to request manually the additional keysets to the eBay support...

**Comment by clotairer** [comment]
@Artem202 make something for multishop to avoid two developper eBay account. He will explain you a workarround. We have not a PR yet.

tx

**Comment by tom-combet** [comment]
Ok, but my use case is not multishop but two distinct PrestaShop installations, will it work too?

**Comment by Artem202** [comment]
Hi @tom-combet,
The module uses "Rename" only during the first connection.
You can try to change the domain of the site in "Runame" which you used for the 1st site, in order to generate a token on the 2nd PrestaShop.

P.S We have never tried using the same account on several sites. It is possible that eBay cancels the first token generated.
P.S2 **Attention**, using the same eBay account in 2 different environments can cause problems with importing orders.
